add wait for qdrant to ci and cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -38,7 +38,7 @@ jobs:
 
       - name: Pull image
         run: |
-          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-1-6:latest"
+          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-2-6:latest"
           docker pull "$IMAGE"
 
       - name: Start Qdrant
@@ -51,9 +51,23 @@ jobs:
             --name qdrant \
             qdrant/qdrant
 
+      - name: Wait for Qdrant
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:6333/health | grep -q '"status":"ok"'; then
+              echo "Qdrant is ready"
+              exit 0
+            fi
+            echo "Waiting for Qdrant..."
+            sleep 2
+          done
+          echo "Qdrant failed to start"
+          docker logs qdrant || true
+          exit 1
+
       - name: Run API container
         run: |
-          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-1-6:latest"
+          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-2-6:latest"
           docker run -d --rm \
             --network app-net \
             --name fashion_api \
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,6 +55,20 @@ jobs:
             --name qdrant \
             qdrant/qdrant
 
+      - name: Wait for Qdrant
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:6333/health | grep -q '"status":"ok"'; then
+              echo "Qdrant is ready"
+              exit 0
+            fi
+            echo "Waiting for Qdrant..."
+            sleep 2
+          done
+          echo "Qdrant failed to start"
+          docker logs qdrant || true
+          exit 1
+
       - name: Configure DVC (DagsHub)
         run: |
           dvc remote modify origin --local access_key_id "${{ secrets.DAGSHUB_ACCESS_KEY }}"
@@ -81,14 +95,14 @@ jobs:
 
       - name: Build and push
         run: |
-          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-1-6:latest"
+          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-2-6:latest"
           docker build -t "$IMAGE" .
           docker push "$IMAGE"
 
       - name: Generate DevSecOps metadata
         run: |
           echo "docker_image:" > dev_sec_ops.yml
-          echo "  name: ${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-1-6" >> dev_sec_ops.yml
+          echo "  name: ${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-2-6" >> dev_sec_ops.yml
           echo "  tag: latest" >> dev_sec_ops.yml
           echo "" >> dev_sec_ops.yml
 
