upd ci / cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -26,18 +26,35 @@ jobs:
 
       - name: Start Qdrant
         run: |
-          docker run -d -p 6333:6333 \
+          docker network create app-net || true
+
+          docker run -d \
+            --network app-net \
             -e QDRANT__SERVICE__API_KEY=${{ secrets.QDRANT_API_KEY }} \
             --name qdrant \
             qdrant/qdrant
+
+      - name: Wait for Qdrant
+        run: |
+          for i in {1..20}; do
+            if curl -s http://localhost:6333/health | grep -q '"status":"ok"'; then
+              echo "Qdrant is ready"
+              exit 0
+            fi
+            echo "Waiting for Qdrant..."
+            sleep 2
+          done
+          echo "Qdrant failed to start"
+          exit 1
 
       - name: Run API container
         run: |
           IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/bd-lab-1-6:latest"
           docker run -d --rm \
+            --network app-net \
             --name fashion_api \
             -p 8000:8000 \
-            -e QDRANT_HOST=host.docker.internal \
+            -e QDRANT_HOST=${{ secrets.QDRANT_PORT }} \
             -e QDRANT_PORT=${{ secrets.QDRANT_PORT }} \
             -e QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }} \
             "$IMAGE"
